# Generated by Django 4.2.17 on 2025-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_area_alter_address_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block_number',
            field=models.CharField(default=12345, max_length=5),
        ),
    ]
