# Generated by Django 4.2.17 on 2025-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
