# Generated by Django 5.1.4 on 2024-12-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, default='images/xyz.jpg', null=True, upload_to='products/'),
        ),
    ]
